### PR TITLE
do not destroy location relations with invalid location updates

### LINKED ISSUE #1885: "Error: Validation failed: Locations is invalid" will reset subject locations to []
Came across this today while playing around with updates to metadata for Diagnosis London subjects in subject set 3492, which have `text/plain` files in the locations array.

Updating a subject without setting the admin flag returns `Error: Validation failed: Locations is invalid`, which I'm pretty sure is correct because we don't officially support text subjects yet?

Anyway, inspecting those subjects after the failed update, the locations array had been reset to [], which I'm pretty sure is a bug. I had a back up of the subject set data, so I was able to update the subject locations manually in admin mode, but this seems like a dangerous bug for any project that needs to update subject metadata.

### PR DESCRIPTION
**Pull request by camallen**
closes #1885 - avoid invalid location updates on the media resource. Make sure these validations pass before updating the relation to reflect the updated location resource.

Describe your change here.

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

File: app/controllers/api/v1/subjects_controller.rb [hunk 1]
```diff
@@ -42,12 +42,16 @@ def build_resource_for_create(create_params)
...
     locations = update_params.delete(:locations)
-    subject = Subject.find(id)
-    subject.locations = add_locations(locations, subject)
-    subject.save!
-    super(update_params, id)
+    locations_update = !locations.blank?
+    if locations_update
+      new_locations = add_locations(locations, resource)
+    end
+    resource.save!
```
Comment (camallen) [inline app/controllers/api/v1/subjects_controller.rb]: actually - think i'll move this to a block for the locations update method.

**Comment by camallen** [comment]
thank you hound for barking at me for a simpler solution...much better now.
