### PR TITLE
Resolves #1514 should not increment classifiers count every time a user performs an action

### LINKED ISSUE #1514: Incorrect project classifiers count
The `events_controller` api is incorrectly updating the project classifier count on all activity messages. It should only count them when the `user_project_preference` is created for the first time and thus indicating a new user for a project.

For reference, the `events_controller` is used to link legacy project activity counts to the new zooniverse api, this is the way we keep counters in sync between legacy projects and older api's.

### PR DESCRIPTION
**Pull request by amyrebecca**
Spec changes were already provided by Cam Allen

Because calling upp.save automatically unsets upp.new_record? I capture the state of upp.new_record? in was_new and then decide whether or not to increment the counter based on that value.

### CODE REVIEW

File: spec/controllers/api/events_controller_spec.rb [hunk 1]
```diff
@@ -171,6 +171,11 @@ def overridden_params(new_params)
           end.to change { UserProjectPreference.count }.from(0).to(1)
         end
 
+        it "should increment the project's classifiers count", :focus do
```
Comment (camallen) [inline spec/controllers/api/events_controller_spec.rb]: still got a `:focus` set on here so the CI only tested those specs, just remove it.

File: spec/controllers/api/events_controller_spec.rb [hunk 2]
```diff
@@ -240,6 +245,11 @@ def overridden_params(new_params)
             end.to_not change { UserProjectPreference.count }.from(1)
           end
 
+          it "should not increment the project's classifiers count", :focus do
```
Comment (camallen) [inline spec/controllers/api/events_controller_spec.rb]: same focus here.

**Comment by camallen** [comment]
LGTM once the full CI runs. Thanks @amyrebecca!
