### PR TITLE
proper etags for singular linked media resources

### LINKED ISSUE #1149: Attempting to delete user avatar or profile_header results in 412
Unsure if I'm doing something incorrect, or if it's related to #1060 

Firing `DELETE` to `/users/1323827/avatar` results in a `{"errors":[{"message":"JsonApiController::PreconditionFailed"}]}` response.

Headers sent below:

```
Accept:application/vnd.api+json; version=1
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Bearer 7437e11947...
Cache-Control:no-cache
Connection:keep-alive
Content-Length:2
Content-Type:application/json
Cookie:tk_tc=143683093....
Host:panoptes-staging.zooniverse.org
If-Match:"7dc995f202f5e8cbbad34f4f2d59e282"
Origin:http://localhost:3735
Pragma:no-cache
Referer:http://localhost:3735/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
```

### PR DESCRIPTION
**Pull request by camallen**
closes #1149 - generate an etag via the index route for linked media has_one relations and modify the precondition check for the media controller.

### CODE REVIEW

File: spec/requests/v1/api_conditional_request_spec.rb [hunk 1]
```diff
@@ -132,18 +135,16 @@
 
     context "index actions" do
       let!(:project) { create_list(:project_with_contents, 2, owner: user).first }
-      let(:url) { "/api/projects" }
+      let!(:url) { "/api/projects" }
```
Comment (edpaget) [inline spec/requests/v1/api_conditional_request_spec.rb]: Not a big deal but I don't think this needs the '!'. I'm kind of curious if you encountered something that caused you to add it.

Comment (camallen) [inline spec/requests/v1/api_conditional_request_spec.rb]: Me being a bit overzealous with my let blocks when trying to figure out the spec ordering and the overriden `precondition_fails?` method.
