### PR TITLE
fix retired? workflow implementation

### LINKED ISSUE #1482: project subject counts should only respect linked subject sets
Project subject_counts should only summate the linked workflow subject sets and not all the project subject sets. Currently `workflow.subject_counts` respects the unlinked state but `project.subjects_count` doesn't. [Change here](https://github.com/zooniverse/Panoptes/blob/59ffad364842e0f326c5d9d3ac7c0e5f20e5780f/app/models/concerns/subject_counts.rb#L5) to use an `active_subject_sets` method differentiates on workfow / project subjects sets.

### LINKED ISSUE #1572: retirement counters dont' take into account unlinked data
as happened on snapshots as sea, the workflow finished and finished counts matched the subjects count but then the owner unlinked all the active sets and added new ones. This left the retired counts much larger and counting old data that wasn't currently active compared to an arbitrary number of currently linked active subjects.

### PR DESCRIPTION
**Pull request by camallen**
closes #1572 and closes #1482. linked to #1640 and #1748 

Don't use the moving subject counts (new / old data being (un)linked) to determine finished state.
Instead use the workflow.finished_at field set by retirement worker.
Also extract subject count methods to the respective models, add project / workflow specific 
behaviour for the subject counts and add a live_subject_sets relation to project 
via the workflows relation to only count the active subject sets in a project.

# Review checklist

* First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
* If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
* If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
* Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

File: app/models/project.rb [hunk 1]
```diff
@@ -127,4 +127,16 @@ def send_notifications
...
+  def subjects_count
+    @subject_count ||= live_subject_sets.sum :set_member_subjects_count
+  end
+
+  def retired_subjects_count
+    @retired_subject_count ||= workflows.sum :retired_set_member_subjects_count
+  end
+
+  def finished?
+    @finished ||= workflows.all? { |w| w.finished_at.present? }
```
Comment (marten) [inline app/models/project.rb]: Couldn't that just be `.all?(&:finished?)`

Comment (camallen) [inline app/models/project.rb]: yep

**Comment by marten** [comment]
LGTM
