### PR TITLE
Fix built-in doorkeeper applicaiton manager

### LINKED ISSUE #1156: Redirect URIs from oauth access_token flow incorrect
Given a link like

`https://panoptes.zooniverse.org/oauth/authorize?response_type=token&client_id=XXXX&redirect_uri=http://localhost:3434/#/classify`

Panoptes will return you to

`http://localhost:3434/#/access_token=XXXXX&token_type=bearer&expires_in=7200`

### PR DESCRIPTION
**Pull request by edpaget**
Can correctly update exisiting applicaitons. Non-admin users can manage
their applications.

Closes #1156

### CODE REVIEW

File: app/controllers/applications_controller.rb [hunk 1]
```diff
@@ -14,13 +16,28 @@ def create
...
       flash[:notice] = I18n.t(:notice, :scope => [:doorkeeper, :flash, :applications, :create])
-       respond_with( :oauth, @application, location: oauth_application_url( @application ) )
+      respond_with :oauth, @application, location: oauth_application_url( @application ) 
     else
       render :new
     end
   end
 
+  def update
+    p "HERE", application_params
```
Comment (camallen) [inline app/controllers/applications_controller.rb]: remove debug statement

**Comment by camallen** [comment]
LGTM after the debug print removal
