### PR TITLE
respect the activated_state of the active workflows

### LINKED ISSUE #2191: Project `active_workflows` ignored deletedness (i.e. `activated_state`)
## Steps to reproduce

* Create project
* Create two workflows and give each of them a distinct subject set with some images
* Mark both workflows as "Active" on the Visibility tab.
* Delete one workflow

*Expected result*: Number of subjects on the project page goes down
*Actual result*: Number of subjects stays the same.

This seems to be the result of `Project#active_workflows` ignoring the `activated_state` of workflows (ignoring the soft-delete).

@camallen pretty sure this isn't intentional, but wanted to double check with you since you added that `Project#active_workflows` scope.

### PR DESCRIPTION
**Pull request by camallen**
Fixes #2191 - don't serialize deleted workflows

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

File: spec/models/project_spec.rb [hunk 1]
```diff
@@ -114,7 +114,7 @@
     end
   end
 
-  describe "#active_workflows" do
+  describe "#active_workflows", :focus do
```
Comment (marten) [inline spec/models/project_spec.rb]: focus left in here
