### PR TITLE
use the reired_at timestamp not created_at

### LINKED ISSUE #2023: Project 2025: retired subject count and % completion incorrectly reported
For the MWP (Project 2025), we are seeing incorrect stats on our workflow stats page.

Retired subject count was approaching 130 but a few days back, it was reset to 3. Just today, the % completion rate was reset to 0% from 17%. 

Anyone know what's going on?

Thanks for your help!

### PR DESCRIPTION
**Pull request by camallen**
fixes #2023 compare apples and apples here as the SubjectWorkflowStatus will be created the first time it's classified not retired.

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

File: spec/counters/workflow_counter_spec.rb [hunk 1]
```diff
@@ -30,9 +30,13 @@
     end
 
     context "with workflow counts" do
+      let(:sws_params) do
+        { workflow: workflow, retired_at: DateTime.now, created_at: DateTime.now + 2.days }
```
Comment (marten) [inline spec/counters/workflow_counter_spec.rb]: Perhaps more realistic would be `DateTime.now - 2.days` ;)

Comment (camallen) [inline spec/counters/workflow_counter_spec.rb]: i explicitly want to test that it's not going to catch these based on created at dates
