### PR TITLE
Fix destroy links routing

### LINKED ISSUE #623: DELETE /links routes uses wrong controller method

### PR DESCRIPTION
**Pull request by edpaget**
Closes #623

### CODE REVIEW

File: spec/support/updatable.rb [hunk 1]
```diff
@@ -100,3 +100,28 @@ def self.extract_linked_resource_ids(linked_resource)
     expect(updated_resource.send(test_relation).map(&:id)).to include(*old_ids)
   end
 end
+
+RSpec.shared_examples "supports destroy_links" do
```
Comment (camallen) [inline spec/support/updatable.rb]: Are these getting called anywhere?

Comment (edpaget) [inline spec/support/updatable.rb]: No I can remove it if you want I was using it to test the user group method until I realized should be deleting members.

Comment (camallen) [inline spec/support/updatable.rb]: Can you clean it up then, best not to leave code lying around that should be removed.
